export type Listing = {
  id: string;
  title: string;
  category: string;
  gender?: "Men" | "Women" | "Unisex" | string;
  occasion: string;
  size: string;
  pricePerDay: number;
  retailPrice: number;
  deposit: number;
  image: string;
  lister: string;
  area: string;
  city: string;
  distanceKm: number;
  rating: number;
  reviews: number;
  verified: boolean;
  fitScore: number;
  unavailableDates?: string[];
  reviewItems?: { author: string; rating: number; date: string; text: string }[];
};

const today = new Date();
const iso = (offset: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + offset);
  return d.toISOString().slice(0, 10);
};
const blockedDates = [iso(2), iso(3), iso(7), iso(8), iso(15), iso(20), iso(21)];
const sampleReviews = [
  { author: "Anita R.", rating: 5, date: "Last month", text: "Pristine condition and the fit was spot-on. Pickup was effortless." },
  { author: "Sneha P.", rating: 5, date: "2 months ago", text: "Got compliments all evening. The lister was responsive and warm." },
  { author: "Vikram J.", rating: 4, date: "3 months ago", text: "Beautiful piece. Slightly tighter than expected, but tailorable on the day." },
];

export const listings: Listing[] = [
  {
    id: "emerald-lehenga",
    title: "Emerald Silk Lehenga",
    category: "Lehenga",
    gender: "Women",
    occasion: "Wedding",
    size: "M",
    pricePerDay: 1800,
    retailPrice: 38000,
    deposit: 6000,
    image: "/assets/hero-lehenga.jpg",
    lister: "Deepa M.",
    area: "Indiranagar",
    city: "Bengaluru",
    distanceKm: 2.4,
    rating: 4.9,
    reviews: 38,
    verified: true,
    fitScore: 94,
  },
  {
    id: "kanjivaram-saree",
    title: "Kanjivaram Silk Saree",
    category: "Saree",
    gender: "Women",
    occasion: "Reception",
    size: "Free",
    pricePerDay: 1200,
    retailPrice: 24000,
    deposit: 4000,
    image: "/assets/item-saree.jpg",
    lister: "Lakshmi R.",
    area: "Koramangala",
    city: "Bengaluru",
    distanceKm: 3.1,
    rating: 4.8,
    reviews: 22,
    verified: true,
    fitScore: 99,
  },
  {
    id: "navy-sherwani",
    title: "Navy Embroidered Sherwani",
    category: "Sherwani",
    gender: "Men",
    occasion: "Wedding",
    size: "L",
    pricePerDay: 1500,
    retailPrice: 32000,
    deposit: 5000,
    image: "/assets/item-sherwani.jpg",
    lister: "Rahul S.",
    area: "HSR Layout",
    city: "Bengaluru",
    distanceKm: 4.6,
    rating: 4.7,
    reviews: 14,
    verified: true,
    fitScore: 88,
  },
  {
    id: "blush-anarkali",
    title: "Blush Chikankari Anarkali",
    category: "Anarkali",
    gender: "Women",
    occasion: "Sangeet",
    size: "S",
    pricePerDay: 950,
    retailPrice: 18500,
    deposit: 3000,
    image: "/assets/item-anarkali.jpg",
    lister: "Priya K.",
    area: "Jayanagar",
    city: "Bengaluru",
    distanceKm: 5.2,
    rating: 4.9,
    reviews: 51,
    verified: true,
    fitScore: 92,
  },
  {
    id: "black-sequin",
    title: "Black Sequin Cocktail Gown",
    category: "Gown",
    gender: "Women",
    occasion: "Cocktail",
    size: "M",
    pricePerDay: 850,
    retailPrice: 15000,
    deposit: 2500,
    image: "/assets/item-cocktail.jpg",
    lister: "Anjali T.",
    area: "Whitefield",
    city: "Bengaluru",
    distanceKm: 8.4,
    rating: 4.6,
    reviews: 19,
    verified: false,
    fitScore: 90,
  },
  {
    id: "ivory-bridal",
    title: "Ivory Gold Bridal Anarkali",
    category: "Anarkali",
    gender: "Women",
    occasion: "Wedding",
    size: "M",
    pricePerDay: 2400,
    retailPrice: 52000,
    deposit: 8000,
    image: "/assets/item-bridal.jpg",
    lister: "Meera J.",
    area: "Indiranagar",
    city: "Bengaluru",
    distanceKm: 2.1,
    rating: 5.0,
    reviews: 12,
    verified: true,
    fitScore: 96,
  },
  {
    id: "teal-kurta",
    title: "Teal Silk Kurta Set",
    category: "Kurta",
    gender: "Men",
    occasion: "Festival",
    size: "M",
    pricePerDay: 600,
    retailPrice: 9500,
    deposit: 1500,
    image: "/assets/item-kurta.jpg",
    lister: "Karan V.",
    area: "Koramangala",
    city: "Bengaluru",
    distanceKm: 3.4,
    rating: 4.7,
    reviews: 28,
    verified: true,
    fitScore: 91,
  },
  {
    id: "comet-aeon-v2-sneakers",
    title: "Comet Unisex Aeon v2 Affogato Sneakers",
    category: "Accessories",
    gender: "Unisex",
    occasion: "Party",
    size: "Free",
    pricePerDay: 350,
    retailPrice: 4499,
    deposit: 1000,
    image: "https://assets.myntassets.com/h_1440,q_100,w_1080/v1/assets/images/2026/JULY/22/S5tWMM0O_6f715edde2304d16ab0dc614633a77e5.jpg",
    lister: "Aditya N.",
    area: "Indiranagar",
    city: "Bengaluru",
    distanceKm: 2.8,
    rating: 4.8,
    reviews: 16,
    verified: true,
    fitScore: 95,
  },
  {
    id: "hm-embroidered-cap",
    title: "H&M Men Embroidered Baseball Cap",
    category: "Accessories",
    gender: "Men",
    occasion: "Festival",
    size: "Free",
    pricePerDay: 150,
    retailPrice: 1299,
    deposit: 400,
    image: "https://assets.myntassets.com/h_1440,q_100,w_1080/v1/assets/images/2026/MAY/27/A7odpRLY_35c4e52583fd4b2abf8ecb5a2674294e.jpg",
    lister: "Rohan M.",
    area: "Koramangala",
    city: "Bengaluru",
    distanceKm: 3.5,
    rating: 4.6,
    reviews: 9,
    verified: true,
    fitScore: 92,
  },
  {
    id: "timex-waterbury-watch",
    title: "Timex Waterbury White Dial Analog Watch",
    category: "Accessories",
    gender: "Unisex",
    occasion: "Formal",
    size: "Free",
    pricePerDay: 650,
    retailPrice: 13995,
    deposit: 2500,
    image: "https://assets.myntassets.com/h_1440,q_100,w_1080/v1/assets/images/2025/FEBRUARY/26/zsn4qxU9_f2557c67ad884b24a01b6110c0398d0c.jpg",
    lister: "Kavya S.",
    area: "Lavelle Road",
    city: "Bengaluru",
    distanceKm: 1.8,
    rating: 4.9,
    reviews: 24,
    verified: true,
    fitScore: 98,
  },
  {
    id: "calvadoss-leather-belt",
    title: "Calvadoss Textured Leather Reversible Belt",
    category: "Accessories",
    gender: "Men",
    occasion: "Formal",
    size: "Free",
    pricePerDay: 120,
    retailPrice: 1999,
    deposit: 300,
    image: "https://assets.myntassets.com/h_1440,q_100,w_1080/v1/assets/images/17825602/2022/4/8/f0be4780-5a8d-4ea3-b6cd-106b1ed0aaad1649432036525CalvadossMenBlackBelts1.jpg",
    lister: "Tarun G.",
    area: "HSR Layout",
    city: "Bengaluru",
    distanceKm: 4.2,
    rating: 4.5,
    reviews: 11,
    verified: true,
    fitScore: 90,
  },
  {
    id: "aristocrat-harbor-trolley",
    title: "Aristocrat Harbor Hard Luggage Trolley (66 cm)",
    category: "Accessories",
    gender: "Unisex",
    occasion: "Wedding",
    size: "Free",
    pricePerDay: 280,
    retailPrice: 6500,
    deposit: 800,
    image: "https://assets.myntassets.com/h_1440,q_100,w_1080/v1/assets/images/2026/FEBRUARY/11/hxSvIeNl_c551a05ef9e44103863a40cdb241e79a.jpg",
    lister: "Vikram R.",
    area: "Sadashivnagar",
    city: "Bengaluru",
    distanceKm: 3.9,
    rating: 4.7,
    reviews: 19,
    verified: true,
    fitScore: 94,
  },
  {
    id: "mufti-floral-shirt",
    title: "Mufti Slim Fit Floral Printed Casual Shirt",
    category: "Shirt",
    gender: "Men",
    occasion: "Sangeet",
    size: "M",
    pricePerDay: 250,
    retailPrice: 2499,
    deposit: 600,
    image: "https://assets.myntassets.com/h_1440,q_100,w_1080/v1/assets/images/2025/DECEMBER/12/5NePCLYD_96fbc1105a6a4de0b1bb3070e1311a7d.jpg",
    lister: "Siddharth B.",
    area: "Indiranagar",
    city: "Bengaluru",
    distanceKm: 2.2,
    rating: 4.8,
    reviews: 31,
    verified: true,
    fitScore: 93,
  },
  {
    id: "rare-rabbit-blazer",
    title: "RARE RABBIT Dexit Tailored Single-Breasted Blazer",
    category: "Blazer",
    gender: "Men",
    occasion: "Reception",
    size: "L",
    pricePerDay: 600,
    retailPrice: 8999,
    deposit: 1500,
    image: "https://assets.myntassets.com/h_1440,q_100,w_1080/v1/assets/images/20030466/2022/9/17/c634f105-f980-4b9c-b1be-30f5039fa9621663416075697Blazers1.jpg",
    lister: "Manish K.",
    area: "Whitefield",
    city: "Bengaluru",
    distanceKm: 6.5,
    rating: 4.9,
    reviews: 27,
    verified: true,
    fitScore: 96,
  },
].map((listing, index) => ({
  ...listing,
  unavailableDates: blockedDates.slice(index % 3, (index % 3) + 4),
  reviewItems: sampleReviews,
}));

export const getListing = (id: string) => listings.find((listing) => listing.id === id);

export const inr = (n: number) => `Rs ${n.toLocaleString("en-IN")}`;

export const isDateBlocked = (listing: Listing, date: Date) =>
  (listing.unavailableDates ?? []).includes(date.toISOString().slice(0, 10));
